# Generated by Django 3.0.2 on 2020-01-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_title',
            field=models.SlugField(max_length=60, null=True, unique=True),
        ),
    ]
