# Generated by Django 3.0.2 on 2020-01-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=45, unique=True)),
                ('posts', models.ManyToManyField(to='posts.Post')),
            ],
        ),
    ]
