# Generated by Django 3.0.2 on 2020-01-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200122_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(related_name='tags', to='posts.Post'),
        ),
    ]
