# Generated by Django 3.0.2 on 2020-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='send_date',
            field=models.DateTimeField(default='2020-02-06 15:28:34'),
        ),
    ]
